### ISSUE TITLE
Deleting data as the Administrator

### ISSUE THREAD

**Issue by michaelbrose** [pmtischler/auvsi_suas_competition#5]
We ran out of space on our server so we tried to clear up space by deleting the previous gps positions, aerial positions, obstacle access logs, and uas telemetry. We are able to manually select individual boxes and delete the selected data, but we are unable to "select all" to delete all the data at once. 
Our team has attempted this in Firefox, chrome, Internet explorer and opera and the same issues occur in all of these browsers. Our team followed this process:
1. Log into the Django administration
2. Clicked on one the link for gps positons or any others
3. From the dropdown menu we selected "delete selected gps positions"
4. Clicked on the "select all gps positions" (This did not select any of the items)

**Comment by pmtischler** [comment]
The system developed does not do anything custom with the Django administrator interface. If you can't get Django's interface to do what you want, you can alternatively directly manipulate the underlying storage layer (currently postgres).

**Comment by pmtischler** [comment]
Django provides a management script called manage.py:
https://docs.djangoproject.com/en/1.8/ref/django-admin/

You can print out command to delete the tables with sqlclear:
https://docs.djangoproject.com/en/1.8/ref/django-admin/#sqlclear-app-label-app-label

You can connect to the database to execute commands with dbshell:
https://docs.djangoproject.com/en/1.8/ref/django-admin/#dbshell

**Comment by michaelbrose** [comment]
Thank you. I was able to clear the database using the flush function
earlier this week. I forgot to respond to tell you that I had resolved the
issue.

**Comment by pmtischler** [comment]
Good to hear. Just looked at the flush function, which seems like the perfect match for this problem.
